# This is a basic workflow to help you get started with Actions

name: Build Razor WebApp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BuildConfig: Release
  SolutionFile: HOW.Selenium.sln

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build with dotnet
      run: dotnet build HOW.Selenium.WebApp/HOW.Selenium.WebApp.csproj
            --configuration ${{ env.BuildConfig }}
            /p:Version=1.0

    - name: Publish
      run: dotnet publish HOW.Selenium.WebApp/HOW.Selenium.WebApp.csproj
    
    - name: Echo Home
      run: echo $HOME

    - name: Echo GITHUB_WORKSPACE
      run: echo $GITHUB_WORKSPACE

    - name: Echo GITHUB_EVENT_NAME
      run: echo $GITHUB_EVENT_NAME

    - name: Echo GITHUB_RUN_NUMBER
      run: echo $GITHUB_RUN_NUMBER

    - name: Upload WebApp Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp1
        path: ${{ github.workspace }}\HOW-Selenium\HOW-Selenium\HOW.Selenium.WebApp\bin\Debug\netcoreapp3.1\publish\
